const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');
const Organization = require('../models/organization.model');

// ==========================================
// PDF REPORT GENERATOR
// ==========================================

const checkNewPage = (doc, yPosition, currentPage, addPageFooter, neededSpace = 100) => {
  if (yPosition + neededSpace > 700) {
    addPageFooter(currentPage, '...');
    doc.addPage();
    return { yPosition: 50, currentPage: currentPage + 1 };
  }
  return { yPosition, currentPage };
};

async function generatePDFReport(doc, transactions, analytics, userCurrency, orgId) {
  let yPosition = 50;
  let currentPage = 1;
  
  const formatCurrency = (value) => {
    const formatted = new Intl.NumberFormat(userCurrency.locale, {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(value);
    const symbols = { 'INR': 'Rs ', 'USD': '$', 'EUR': '€', 'GBP': '£', 'JPY': '¥', 'AUD': 'A$', 'CAD': 'C$' };
    const symbol = symbols[userCurrency.code] || `${userCurrency.code} `;
    return `${symbol}${formatted}`;
  };
  
  const addPageFooter = (pageNum, totalPages) => {
    const footerY = 750;
    doc.fontSize(8).fillColor('#999').text(`Page ${pageNum} | Generated by Accountly Transparency`, 50, footerY, { align: 'center', width: 495 });
  };
  
  let orgFields = [];
  try {
    const org = await Organization.findById(orgId).lean();
    if (org && org.contributorFields) {
      orgFields = org.contributorFields.filter(f => f.publicVisibility === 'visible');
    }
  } catch (e) {
    console.error('Error fetching org fields for PDF:', e);
  }

  // Header
  doc.fontSize(24).fillColor('#2D3748').text('ACCOUNTLY FINANCIAL REPORT', 50, yPosition, { align: 'center' });
  yPosition += 35;
  doc.fontSize(10).fillColor('#718096').text(`Generated on: ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}`, 50, yPosition, { align: 'center' });
  yPosition += 15;
  doc.fontSize(10).text(`Report Period: ${analytics.period.type.toUpperCase()}`, 50, yPosition, { align: 'center' });
  yPosition += 40;
  
  let state;

  // 1. Executive Summary
  state = checkNewPage(doc, yPosition, currentPage, addPageFooter, 120);
  yPosition = state.yPosition; currentPage = state.currentPage;
  doc.rect(50, yPosition, 495, 90).fill('#F7FAFC').stroke('#E2E8F0');
  yPosition += 15;
  doc.fontSize(14).fillColor('#2D3748').text('1. Executive Summary', 70, yPosition);
  yPosition += 25;
  doc.fontSize(10).fillColor('#4A5568');
  doc.text('Total Collected:', 70, yPosition).text(formatCurrency(analytics.summary.totalCollected), 170, yPosition);
  doc.text('Total Spent:', 320, yPosition).text(formatCurrency(analytics.summary.totalSpent), 420, yPosition);
  yPosition += 18;
  doc.text('Remaining Balance:', 70, yPosition).fillColor(analytics.summary.remainingBalance >= 0 ? '#38A169' : '#E53E3E').text(formatCurrency(analytics.summary.remainingBalance), 170, yPosition);
  doc.fillColor('#4A5568').text('Spending Ratio:', 320, yPosition).text(`${analytics.ratios.spendingRatio.toFixed(1)}%`, 420, yPosition);
  yPosition += 40;

  // 2. Contribution Overview
  state = checkNewPage(doc, yPosition, currentPage, addPageFooter, 100);
  yPosition = state.yPosition; currentPage = state.currentPage;
  doc.fontSize(14).fillColor('#2D3748').text('2. Contribution Overview', 50, yPosition);
  yPosition += 20;
  doc.fontSize(10).fillColor('#4A5568');
  doc.text(`Total Contributions: ${analytics.summary.contributionCount}`, 50, yPosition);
  doc.text(`Average Contribution: ${formatCurrency(analytics.contributions.average)}`, 200, yPosition);
  doc.text(`Largest Contribution: ${formatCurrency(analytics.contributions.largest)}`, 350, yPosition);
  yPosition += 35;

  // 3. Contribution Group Breakdown
  if (analytics.contributions.byCategory && analytics.contributions.byCategory.length > 0) {
    state = checkNewPage(doc, yPosition, currentPage, addPageFooter, 120);
    yPosition = state.yPosition; currentPage = state.currentPage;
    doc.fontSize(14).fillColor('#2D3748').text('3. Contribution Group Breakdown', 50, yPosition);
    yPosition += 20;
    doc.rect(50, yPosition, 495, 20).fill('#EDF2F7').stroke('#CBD5E0');
    doc.fontSize(9).fillColor('#2D3748');
    doc.text('Category', 60, yPosition + 6);
    doc.text('Amount', 250, yPosition + 6);
    doc.text('Count', 400, yPosition + 6);
    yPosition += 20;
    analytics.contributions.byCategory.forEach((cat, index) => {
      state = checkNewPage(doc, yPosition, currentPage, addPageFooter, 25);
      yPosition = state.yPosition; currentPage = state.currentPage;
      doc.rect(50, yPosition, 495, 18).fill(index % 2 === 0 ? '#FFFFFF' : '#F7FAFC').stroke('#E2E8F0');
      doc.fontSize(9).fillColor('#4A5568');
      doc.text(String(cat.category || 'Other').substring(0, 30), 60, yPosition + 5);
      doc.text(formatCurrency(cat.amount), 250, yPosition + 5);
      doc.text(cat.count.toString(), 400, yPosition + 5);
      yPosition += 18;
    });
    yPosition += 20;
  }

  // 4. Expense Overview
  state = checkNewPage(doc, yPosition, currentPage, addPageFooter, 80);
  yPosition = state.yPosition; currentPage = state.currentPage;
  doc.fontSize(14).fillColor('#2D3748').text('4. Expense Breakdown', 50, yPosition);
  yPosition += 20;
  doc.fontSize(10).fillColor('#4A5568');
  doc.text(`Total Expenses: ${analytics.summary.expenseCount}`, 50, yPosition);
  doc.text(`Average Expense: ${formatCurrency(analytics.expenses.average)}`, 200, yPosition);
  doc.text(`Largest Expense: ${formatCurrency(analytics.expenses.largest)}`, 350, yPosition);
  yPosition += 35;

  // 5. Expense Category Analysis
  if (analytics.expenses.byCategory && analytics.expenses.byCategory.length > 0) {
    state = checkNewPage(doc, yPosition, currentPage, addPageFooter, 120);
    yPosition = state.yPosition; currentPage = state.currentPage;
    doc.fontSize(14).fillColor('#2D3748').text('5. Expense Category Analysis', 50, yPosition);
    yPosition += 20;
    doc.rect(50, yPosition, 495, 20).fill('#EDF2F7').stroke('#CBD5E0');
    doc.fontSize(9).fillColor('#2D3748');
    doc.text('Category', 60, yPosition + 6);
    doc.text('Amount', 250, yPosition + 6);
    doc.text('Count', 400, yPosition + 6);
    yPosition += 20;
    analytics.expenses.byCategory.forEach((cat, index) => {
      state = checkNewPage(doc, yPosition, currentPage, addPageFooter, 25);
      yPosition = state.yPosition; currentPage = state.currentPage;
      doc.rect(50, yPosition, 495, 18).fill(index % 2 === 0 ? '#FFFFFF' : '#F7FAFC').stroke('#E2E8F0');
      doc.fontSize(9).fillColor('#4A5568');
      doc.text(String(cat.category || 'Other').substring(0, 30), 60, yPosition + 5);
      doc.text(formatCurrency(cat.amount), 250, yPosition + 5);
      doc.text(cat.count.toString(), 400, yPosition + 5);
      yPosition += 18;
    });
    yPosition += 20;
  }

  // 6. Financial Trends
  if (analytics.expenses.trends && analytics.expenses.trends.length > 0) {
    state = checkNewPage(doc, yPosition, currentPage, addPageFooter, 150);
    yPosition = state.yPosition; currentPage = state.currentPage;
    doc.fontSize(14).fillColor('#2D3748').text('6. Financial Trends', 50, yPosition);
    yPosition += 20;
    doc.rect(50, yPosition, 495, 20).fill('#EDF2F7').stroke('#CBD5E0');
    doc.fontSize(9).fillColor('#2D3748');
    doc.text('Month', 60, yPosition + 6);
    doc.text('Collected', 180, yPosition + 6);
    doc.text('Spent', 300, yPosition + 6);
    doc.text('Balance', 420, yPosition + 6);
    yPosition += 20;
    analytics.expenses.trends.forEach((t, index) => {
      state = checkNewPage(doc, yPosition, currentPage, addPageFooter, 25);
      yPosition = state.yPosition; currentPage = state.currentPage;
      doc.rect(50, yPosition, 495, 18).fill(index % 2 === 0 ? '#FFFFFF' : '#F7FAFC').stroke('#E2E8F0');
      doc.fontSize(9).fillColor('#4A5568');
      doc.text(t.month, 60, yPosition + 5);
      doc.text(formatCurrency(t.collected), 180, yPosition + 5);
      doc.text(formatCurrency(t.spent), 300, yPosition + 5);
      doc.fillColor(t.remainingBalance >= 0 ? '#38A169' : '#E53E3E').text(formatCurrency(t.remainingBalance), 420, yPosition + 5);
      yPosition += 18;
    });
    yPosition += 30;
  }

  // Detailed Records Header Builder
  const buildDetailHeader = (title) => {
    state = checkNewPage(doc, yPosition, currentPage, addPageFooter, 100);
    yPosition = state.yPosition; currentPage = state.currentPage;
    doc.fontSize(14).fillColor('#2D3748').text(title, 50, yPosition);
    yPosition += 20;
  };

  // 7. Detailed Contributions
  const contributions = transactions.filter(t => t.type === 'contribution');
  if (contributions.length > 0) {
    buildDetailHeader('7. Detailed Contributions');
    doc.rect(50, yPosition, 495, 20).fill('#EDF2F7').stroke('#CBD5E0');
    doc.fontSize(8).fillColor('#2D3748');
    doc.text('Date', 60, yPosition + 6);
    doc.text('Contributor', 120, yPosition + 6);
    doc.text('Category', 220, yPosition + 6);
    
    let metaX = 300;
    const cols = orgFields.slice(0, 2);
    cols.forEach(f => {
      doc.text(f.label.substring(0, 10), metaX, yPosition + 6);
      metaX += 60;
    });
    doc.text('Amount', 440, yPosition + 6);
    yPosition += 20;

    contributions.forEach((t, i) => {
      state = checkNewPage(doc, yPosition, currentPage, addPageFooter, 25);
      yPosition = state.yPosition; currentPage = state.currentPage;
      doc.rect(50, yPosition, 495, 18).fill(i % 2 === 0 ? '#FFFFFF' : '#F7FAFC').stroke('#E2E8F0');
      doc.fontSize(8).fillColor('#4A5568');
      doc.text(new Date(t.date).toLocaleDateString(), 60, yPosition + 5);
      doc.text(String(t.contributor?.name || 'Unknown').substring(0, 15), 120, yPosition + 5);
      doc.text(String(t.category || '').substring(0, 12), 220, yPosition + 5);
      
      let mx = 300;
      if (t.contributor?.metadata) {
        const meta = typeof t.contributor.metadata.get === 'function' ? Object.fromEntries(t.contributor.metadata) : t.contributor.metadata;
        cols.forEach(f => {
          doc.text(String(meta[f.key] || '').substring(0, 10), mx, yPosition + 5);
          mx += 60;
        });
      }
      doc.text(formatCurrency(t.amount), 440, yPosition + 5);
      yPosition += 18;
    });
    yPosition += 30;
  }

  // 8. Detailed Expenses
  const expenses = transactions.filter(t => t.type === 'expense');
  if (expenses.length > 0) {
    buildDetailHeader('8. Detailed Expenses');
    doc.rect(50, yPosition, 495, 20).fill('#EDF2F7').stroke('#CBD5E0');
    doc.fontSize(8).fillColor('#2D3748');
    doc.text('Date', 60, yPosition + 6);
    doc.text('Category', 120, yPosition + 6);
    doc.text('Recipient', 220, yPosition + 6);
    doc.text('Description', 320, yPosition + 6);
    doc.text('Amount', 440, yPosition + 6);
    yPosition += 20;

    expenses.forEach((t, i) => {
      state = checkNewPage(doc, yPosition, currentPage, addPageFooter, 25);
      yPosition = state.yPosition; currentPage = state.currentPage;
      doc.rect(50, yPosition, 495, 18).fill(i % 2 === 0 ? '#FFFFFF' : '#F7FAFC').stroke('#E2E8F0');
      doc.fontSize(8).fillColor('#4A5568');
      doc.text(new Date(t.date).toLocaleDateString(), 60, yPosition + 5);
      doc.text(String(t.category || '').substring(0, 15), 120, yPosition + 5);
      doc.text(String(t.recipient?.name || '').substring(0, 15), 220, yPosition + 5);
      doc.text(String(t.description || '').substring(0, 18), 320, yPosition + 5);
      doc.text(formatCurrency(t.amount), 440, yPosition + 5);
      yPosition += 18;
    });
  }

  addPageFooter(currentPage, currentPage);
}

// ==========================================
// EXCEL REPORT GENERATOR
// ==========================================
async function generateExcelReport(transactions, analytics, userCurrency, orgId) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Accountly';
  workbook.created = new Date();

  let orgFields = [];
  try {
    const org = await Organization.findById(orgId).lean();
    if (org && org.contributorFields) {
      orgFields = org.contributorFields.filter(f => f.publicVisibility === 'visible');
    }
  } catch (e) {
    console.error('Error fetching org fields for Excel:', e);
  }

  // 1. Summary Sheet
  const summarySheet = workbook.addWorksheet('Summary');
  summarySheet.columns = [ { header: 'Metric', key: 'metric', width: 25 }, { header: 'Value', key: 'value', width: 20 } ];
  summarySheet.getRow(1).font = { bold: true };
  
  summarySheet.addRows([
    { metric: 'Report Period', value: analytics.period.type.toUpperCase() },
    { metric: 'Generated On', value: new Date().toLocaleDateString() },
    { metric: '' },
    { metric: 'Total Collected', value: analytics.summary.totalCollected },
    { metric: 'Total Spent', value: analytics.summary.totalSpent },
    { metric: 'Remaining Balance', value: analytics.summary.remainingBalance },
    { metric: '' },
    { metric: 'Contribution Count', value: analytics.summary.contributionCount },
    { metric: 'Expense Count', value: analytics.summary.expenseCount },
    { metric: 'Spending Ratio (%)', value: analytics.ratios.spendingRatio }
  ]);

  // Format currencies
  [4, 5, 6].forEach(r => {
    summarySheet.getCell(`B${r}`).numFmt = `"${userCurrency.code}" #,##0.00`;
  });

  // 2. Contributions Sheet
  const contribSheet = workbook.addWorksheet('Contributions');
  const contribCols = [
    { header: 'Date', key: 'date', width: 15 },
    { header: 'Contributor', key: 'contributor', width: 25 },
    { header: 'Category', key: 'category', width: 20 },
    { header: 'Amount', key: 'amount', width: 15 },
    { header: 'Status', key: 'status', width: 15 }
  ];
  
  orgFields.forEach(f => {
    contribCols.push({ header: f.label, key: f.key, width: 20 });
  });
  
  contribSheet.columns = contribCols;
  contribSheet.getRow(1).font = { bold: true };

  transactions.filter(t => t.type === 'contribution').forEach(t => {
    const rowData = {
      date: new Date(t.date).toLocaleDateString(),
      contributor: t.contributor?.name || 'Unknown',
      category: t.category || '',
      amount: t.amount,
      status: t.status || 'completed'
    };
    if (t.contributor?.metadata) {
      const meta = typeof t.contributor.metadata.get === 'function' ? Object.fromEntries(t.contributor.metadata) : t.contributor.metadata;
      orgFields.forEach(f => {
        rowData[f.key] = meta[f.key] || '';
      });
    }
    contribSheet.addRow(rowData);
  });
  contribSheet.getColumn('amount').numFmt = `"${userCurrency.code}" #,##0.00`;

  // 3. Expenses Sheet
  const expenseSheet = workbook.addWorksheet('Expenses');
  expenseSheet.columns = [
    { header: 'Date', key: 'date', width: 15 },
    { header: 'Category', key: 'category', width: 20 },
    { header: 'Recipient', key: 'recipient', width: 25 },
    { header: 'Description', key: 'description', width: 35 },
    { header: 'Amount', key: 'amount', width: 15 }
  ];
  expenseSheet.getRow(1).font = { bold: true };

  transactions.filter(t => t.type === 'expense').forEach(t => {
    expenseSheet.addRow({
      date: new Date(t.date).toLocaleDateString(),
      category: t.category || '',
      recipient: t.recipient?.name || '',
      description: t.description || '',
      amount: t.amount
    });
  });
  expenseSheet.getColumn('amount').numFmt = `"${userCurrency.code}" #,##0.00`;

  // 4. Analytics Sheet
  const analyticsSheet = workbook.addWorksheet('Analytics');
  analyticsSheet.columns = [ { header: 'Category', key: 'cat', width: 25 }, { header: 'Expense Amount', key: 'exp', width: 20 }, { header: 'Contribution Amount', key: 'con', width: 20 } ];
  analyticsSheet.getRow(1).font = { bold: true };
  
  const allCats = new Set([...(analytics.expenses.byCategory || []).map(c => c.category), ...(analytics.contributions.byCategory || []).map(c => c.category)]);
  
  allCats.forEach(cat => {
    const expRow = (analytics.expenses.byCategory || []).find(c => c.category === cat);
    const conRow = (analytics.contributions.byCategory || []).find(c => c.category === cat);
    analyticsSheet.addRow({
      cat: cat || 'Other',
      exp: expRow ? expRow.amount : 0,
      con: conRow ? conRow.amount : 0
    });
  });
  analyticsSheet.getColumn('exp').numFmt = `"${userCurrency.code}" #,##0.00`;
  analyticsSheet.getColumn('con').numFmt = `"${userCurrency.code}" #,##0.00`;

  return workbook.xlsx.writeBuffer();
}

module.exports = {
  generatePDFReport,
  generateExcelReport
};
