const PDFDocument = require('pdfkit');

// Helper function to check if we need a new page
const checkNewPage = (doc, yPosition, currentPage, addPageFooter, neededSpace = 100) => {
  if (yPosition > 700) {
    addPageFooter(currentPage, '...');
    doc.addPage();
    return { yPosition: 50, currentPage: currentPage + 1 };
  }
  return { yPosition, currentPage };
};

// Main PDF generation function
async function generatePDFReport(doc, transactions, stats, userCurrency) {
  let yPosition = 50;
  let currentPage = 1;
  
  // Currency formatting helper
  const formatCurrency = (value) => {
    const formatted = new Intl.NumberFormat(userCurrency.locale, {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(value);

    // Map currency codes to symbols safe for PDFKit (Standard Fonts)
    const symbols = {
      'INR': 'Rs ', // Rupee symbol ₹ is not supported in standard PDF fonts
      'USD': '$',
      'EUR': '€',
      'GBP': '£',
      'JPY': '¥',
      'AUD': 'A$',
      'CAD': 'C$',
    };

    const symbol = symbols[userCurrency.code] || `${userCurrency.code} `;
    return `${symbol}${formatted}`;
  };
  
  // Helper function to add page footer
  const addPageFooter = (pageNum, totalPages) => {
    const footerY = 750;
    doc.fontSize(8).fillColor('#999').text(
      `Page ${pageNum} of ${totalPages} | Generated by Accountly`, 
      50, 
      footerY, 
      { align: 'center', width: 495 }
    );
  };
  
  // Header
  doc.fontSize(24).fillColor('#2D3748').text('ACCOUNTLY - FINANCIAL REPORT', 50, yPosition, { align: 'center' });
  yPosition += 40;
  
  doc.fontSize(12).fillColor('#666').text(`Generated on: ${new Date().toLocaleDateString('en-US', { 
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' 
  })}`, 50, yPosition, { align: 'center' });
  yPosition += 20;
  
  doc.fontSize(10).text(`Report Period: ${transactions.length > 0 ? new Date(transactions[transactions.length - 1].date).toLocaleDateString() : 'N/A'} to ${transactions.length > 0 ? new Date(transactions[0].date).toLocaleDateString() : 'N/A'}`, 50, yPosition, { align: 'center' });
  yPosition += 40;
  
  // Executive Summary Box
  let state = checkNewPage(doc, yPosition, currentPage, addPageFooter);
  yPosition = state.yPosition; currentPage = state.currentPage;

  doc.rect(50, yPosition, 495, 120).fill('#F7FAFC').stroke('#E2E8F0');
  yPosition += 15;
  
  doc.fontSize(16).fillColor('#2D3748').text('EXECUTIVE SUMMARY', 70, yPosition);
  yPosition += 25;
  
  // Summary stats in columns
  const leftCol = 70;
  const rightCol = 320;
  
  doc.fontSize(11).fillColor('#4A5568');
  doc.text('Total Collected:', leftCol, yPosition).text(formatCurrency(stats.periods.allTime.collected), leftCol + 100, yPosition);
  doc.text('This Month Collected:', rightCol, yPosition).text(formatCurrency(stats.periods.thisMonth.collected), rightCol + 130, yPosition);
  yPosition += 18;
  
  doc.text('Total Spent:', leftCol, yPosition).text(formatCurrency(stats.periods.allTime.spent), leftCol + 100, yPosition);
  doc.text('This Month Spent:', rightCol, yPosition).text(formatCurrency(stats.periods.thisMonth.spent), rightCol + 130, yPosition);
  yPosition += 18;
  
  doc.text('Remaining Balance:', leftCol, yPosition).fillColor(stats.periods.allTime.remainingBalance >= 0 ? '#38A169' : '#E53E3E').text(formatCurrency(stats.periods.allTime.remainingBalance), leftCol + 110, yPosition);
  doc.fillColor('#4A5568').text('Retention Rate:', rightCol, yPosition).text(`${stats.periods.thisMonth.retentionRate.toFixed(1)}%`, rightCol + 130, yPosition);
  yPosition += 18;
  
  doc.text('Total Records:', leftCol, yPosition).text(stats.totalTransactions.toString(), leftCol + 100, yPosition);
  doc.text('Avg Transaction:', rightCol, yPosition).text(formatCurrency(stats.periods.allTime.avgTransaction), rightCol + 130, yPosition);
  yPosition += 30;
  
  // Key Insights
  state = checkNewPage(doc, yPosition, currentPage, addPageFooter, 100);
  yPosition = state.yPosition; currentPage = state.currentPage;

  doc.fontSize(14).fillColor('#2D3748').text('KEY FINANCIAL INSIGHTS', 50, yPosition);
  yPosition += 20;
  
  stats.insights.forEach((insight) => {
    state = checkNewPage(doc, yPosition, currentPage, addPageFooter);
    yPosition = state.yPosition; currentPage = state.currentPage;

    doc.fontSize(10).fillColor('#4A5568').text(`• ${insight}`, 70, yPosition);
    yPosition += 15;
  });
  yPosition += 20;
  
  // Top Expense Categories
  state = checkNewPage(doc, yPosition, currentPage, addPageFooter, 150);
  yPosition = state.yPosition; currentPage = state.currentPage;

  doc.fontSize(14).fillColor('#2D3748').text('TOP EXPENSE CATEGORIES', 50, yPosition);
  yPosition += 25;
  
  // Table header
  doc.rect(50, yPosition, 495, 25).fill('#EDF2F7').stroke('#CBD5E0');
  doc.fontSize(10).fillColor('#2D3748');
  doc.text('Category', 60, yPosition + 8);
  doc.text('Amount', 200, yPosition + 8);
  doc.text('Transactions', 300, yPosition + 8);
  doc.text('Avg per Transaction', 420, yPosition + 8);
  yPosition += 25;
  
  stats.topExpenseCategories.forEach((cat, index) => {
    state = checkNewPage(doc, yPosition, currentPage, addPageFooter);
    yPosition = state.yPosition; currentPage = state.currentPage;

    const bgColor = index % 2 === 0 ? '#FFFFFF' : '#F7FAFC';
    doc.rect(50, yPosition, 495, 20).fill(bgColor).stroke('#E2E8F0');
    doc.fontSize(9).fillColor('#4A5568');
    doc.text(cat.category.substring(0, 20), 60, yPosition + 6);
    doc.text(formatCurrency(cat.amount), 200, yPosition + 6);
    doc.text(cat.count.toString(), 320, yPosition + 6);
    doc.text(formatCurrency(cat.amount / cat.count), 440, yPosition + 6);
    yPosition += 20;
  });
  yPosition += 20;
  
  // Monthly Trends Chart (Text-based)
  state = checkNewPage(doc, yPosition, currentPage, addPageFooter, 200);
  yPosition = state.yPosition; currentPage = state.currentPage;

  doc.fontSize(14).fillColor('#2D3748').text('MONTHLY TRENDS (Last 12 Months)', 50, yPosition);
  yPosition += 25;
  
  // Chart header
  doc.rect(50, yPosition, 495, 25).fill('#EDF2F7').stroke('#CBD5E0');
  doc.fontSize(10).fillColor('#2D3748');
  doc.text('Month', 60, yPosition + 8);
  doc.text('Collected', 140, yPosition + 8);
  doc.text('Spent', 220, yPosition + 8);
  doc.text('Remaining', 300, yPosition + 8);
  doc.text('Retention', 380, yPosition + 8);
  doc.text('Records', 480, yPosition + 8);
  yPosition += 25;
  
  stats.monthlyTrends.forEach((trend, index) => {
    state = checkNewPage(doc, yPosition, currentPage, addPageFooter);
    yPosition = state.yPosition; currentPage = state.currentPage;

    const bgColor = index % 2 === 0 ? '#FFFFFF' : '#F7FAFC';
    doc.rect(50, yPosition, 495, 20).fill(bgColor).stroke('#E2E8F0');
    doc.fontSize(9).fillColor('#4A5568');
    doc.text(trend.month, 60, yPosition + 6);
    doc.text(formatCurrency(trend.collected), 140, yPosition + 6);
    doc.text(formatCurrency(trend.spent), 220, yPosition + 6);
    doc.fillColor(trend.remainingBalance >= 0 ? '#38A169' : '#E53E3E').text(formatCurrency(trend.remainingBalance), 300, yPosition + 6);
    doc.fillColor('#4A5568').text(`${trend.retentionRate.toFixed(1)}%`, 380, yPosition + 6);
    doc.text(trend.count.toString(), 485, yPosition + 6);
    yPosition += 20;
  });
  yPosition += 30;
  
  // Detailed Transaction History
  addPageFooter(currentPage, '...');
  doc.addPage();
  currentPage++;
  yPosition = 50;
  
  doc.fontSize(14).fillColor('#2D3748').text('FINANCIAL RECORD HISTORY', 50, yPosition);
  yPosition += 25;
  
  // Transaction table header
  doc.rect(50, yPosition, 495, 25).fill('#EDF2F7').stroke('#CBD5E0');
  doc.fontSize(9).fillColor('#2D3748');
  doc.text('Date', 60, yPosition + 8);
  doc.text('Type', 130, yPosition + 8);
  doc.text('Category', 180, yPosition + 8);
  doc.text('Amount', 280, yPosition + 8);
  doc.text('Description', 350, yPosition + 8);
  yPosition += 25;
  
  let runningBalance = 0;
  transactions.slice().reverse().forEach((t, index) => {
    if (index >= 50) return; // Limit to recent 50 transactions
    
    state = checkNewPage(doc, yPosition, currentPage, addPageFooter);
    yPosition = state.yPosition; currentPage = state.currentPage;

    const amount = parseFloat(t.amount);
    runningBalance += (t.type === 'contribution' ? amount : -amount);
    
    const bgColor = index % 2 === 0 ? '#FFFFFF' : '#F7FAFC';
    doc.rect(50, yPosition, 495, 18).fill(bgColor).stroke('#E2E8F0');
    
    doc.fontSize(8).fillColor('#4A5568');
    doc.text(new Date(t.date).toLocaleDateString(), 60, yPosition + 5);
    doc.fillColor(t.type === 'contribution' ? '#38A169' : '#E53E3E').text(t.type.toUpperCase(), 130, yPosition + 5);
    doc.fillColor('#4A5568').text(t.category.substring(0, 12), 180, yPosition + 5);
    doc.text(formatCurrency(amount), 280, yPosition + 5);
    doc.text(String(t.description || '').substring(0, 25), 350, yPosition + 5);
    yPosition += 18;
  });
  
  // Add footer to last page
  addPageFooter(currentPage, currentPage);
}

module.exports = {
  generatePDFReport
};
